services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: market_hokey_pokey_db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - market_hokey_pokey_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 8s
      timeout: 8s
      retries: 5

volumes:
  market_hokey_pokey_db_data:
